version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tracker
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tracker" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  liquibase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: liquibase
    depends_on:
      db:
        condition: service_healthy
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/tracker
      JDBC_USERNAME: postgres
      JDBC_PASSWORD: password
      JDBC_DRIVER: org.postgresql.Driver
    command: mvn -Pdocker liquibase:update
    restart: "no"

  job4j_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/tracker
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: job4j_tracker
    depends_on:
      - db
      - liquibase